name: CI workflow

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip

            - name: Run basic test
              run: echo "Test"

            - name: Build Docker image
              run: docker build -t flask-app .

            - name: Run Trivy scan
              run: |
                  docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image flask-app

            - name: Push to GitHub Container Registry
              if: github.event_name == 'push'
              run: |
                  echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
                  docker tag flask-app ghcr.io/${{ github.repository_owner }}/flask-app:latest
                  docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest
